name = "imc-api"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "BD"
database_name = "imc-database"
database_id = "${CLOUDFLARE_DATABASE_ID}"
preview_database_id = "${CLOUDFLARE_DATABASE_ID}"